name: deploy

on:
  workflow_dispatch:
    inputs:
      nnum:
        required: true
        type: string
      ntype:
        required: true
        type: string
      ntitle:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Inputs Processing
        run: |
          echo "${{github.event.inputs.nnum}}" >> data/toki/number.txt
          echo "${{github.event.inputs.ntitle}}" > data/toki/newtoki/${{github.event.inputs.ntype}}.txt

      - name: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Github Actions"
          git push